# DataFrames III: Data Extraction

In [2]:
import pandas as pd

## This Module's Dataset
- This module's dataset is a collection of all James Bond movies.

In [21]:
bond = pd.read_csv("jamesbond.csv")
bond.info()
bond.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Film               27 non-null     object
 1   Year               27 non-null     int64
 2   Actor              27 non-null     object
 3   Director           27 non-null     object
 4   Box Office         27 non-null     float64
 5   Budget             27 non-null     float64
 6   Bond Actor Salary  20 non-null     float64
dtypes: float64(3), int64(1), object(3)
memory usage: 1.6+ KB

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

## The set_index and reset_index Methods
- The index serves as the collection of primary identifiers/labels/entrypoints for the rows.
- The fastest way to extract a row is from a sorted index by position/label.
- Pandas uses index labels/values when merging different objects together.
- The `set_index` method sets an existing column as the index of the **DataFrame**.
- The `reset_index` method sets the standard ascending numeric index as the index of the **DataFrame**.

In [ ]:
 #for large tables, define an index, sort the index, and then filter the rows. This is the fastest method in pandas

In [27]:
bond.set_index("Film")

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0

In [30]:
bond.reset_index(drop=True)

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
5,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
6,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
7,Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
8,Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
9,The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
10,The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
11,Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
12,For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
13,Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
14,Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
15,A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
16,The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
17,Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
18,GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
19,Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
21,Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
22,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
26,No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0

In [31]:
bond.set_index("Film")

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0

In [32]:
bond.reset_index().set_index("Year")

,index,Film,Actor,Director,Box Office,Budget,Bond Actor Salary
Year,,,,,,,
1962,0,Dr. No,Sean Connery,Terence Young,448.8,7.0,0.6
1963,1,From Russia with Love,Sean Connery,Terence Young,543.8,12.6,1.6
1964,2,Goldfinger,Sean Connery,Guy Hamilton,820.4,18.6,3.2
1965,3,Thunderball,Sean Connery,Terence Young,848.1,41.9,4.7
1967,4,Casino Royale,David Niven,Ken Hughes,315.0,85.0,NaN
1967,5,You Only Live Twice,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
1969,6,On Her Majesty's Secret Service,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
1971,7,Diamonds Are Forever,Sean Connery,Guy Hamilton,442.5,34.7,5.8
1973,8,Live and Let Die,Roger Moore,Guy Hamilton,460.3,30.8,NaN
1974,9,The Man with the Golden Gun,Roger Moore,Guy Hamilton,334.0,27.7,NaN
1977,10,The Spy Who Loved Me,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
1979,11,Moonraker,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
1981,12,For Your Eyes Only,Roger Moore,John Glen,449.4,60.2,NaN
1983,13,Never Say Never Again,Sean Connery,Irvin Kershner,380.0,86.0,NaN
1983,14,Octopussy,Roger Moore,John Glen,373.8,53.9,7.8
1985,15,A View to a Kill,Roger Moore,John Glen,275.2,54.5,9.1
1987,16,The Living Daylights,Timothy Dalton,John Glen,313.5,68.8,5.2
1989,17,Licence to Kill,Timothy Dalton,John Glen,250.9,56.7,7.9
1995,18,GoldenEye,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
1997,19,Tomorrow Never Dies,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
1999,20,The World Is Not Enough,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
2002,21,Die Another Day,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
2006,22,Casino Royale,Daniel Craig,Martin Campbell,581.5,145.3,3.3
2008,23,Quantum of Solace,Daniel Craig,Marc Forster,514.2,181.4,8.1
2012,24,Skyfall,Daniel Craig,Sam Mendes,943.5,170.2,14.5
2015,25,Spectre,Daniel Craig,Sam Mendes,726.7,206.3,30.0
2021,26,No Time to Die,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0

In [36]:
bond.reset_index(drop=True)

,index,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
5,5,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
6,6,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
7,7,Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
8,8,Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
9,9,The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
10,10,The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
11,11,Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
12,12,For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
13,13,Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
14,14,Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
15,15,A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
16,16,The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
17,17,Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
18,18,GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
19,19,Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
20,20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
21,21,Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
22,22,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,25,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
26,26,No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0

In [41]:
bond = bond.reset_index().set_index("Film")
bond.head()

,level_0,index,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,,,
Dr. No,0,0,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1,1,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,2,2,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,3,3,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Casino Royale,4,4,1967,David Niven,Ken Hughes,315.0,85.0,NaN

## Retrieve Rows by Index Position with iloc Accessor
- The `iloc` accessor retrieves one or more rows by index position.
- Provide a pair of square brackets after the accessor.
- `iloc` accepts single values, lists, and slices.

In [43]:
bond = pd.read_csv("jamesbond.csv")
bond.info()
bond.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Film               27 non-null     object
 1   Year               27 non-null     int64
 2   Actor              27 non-null     object
 3   Director           27 non-null     object
 4   Box Office         27 non-null     float64
 5   Budget             27 non-null     float64
 6   Bond Actor Salary  20 non-null     float64
dtypes: float64(3), int64(1), object(3)
memory usage: 1.6+ KB

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [44]:
bond.iloc[5] # selects rows based on the numeric index

Film                 You Only Live Twice
Year                                1967
Actor                       Sean Connery
Director                   Lewis Gilbert
Box Office                         514.2
Budget                              59.9
Bond Actor Salary                    4.4
Name: 5, dtype: object

In [45]:
bond.iloc[[10, 12]] #There are double brackets.  The first is because it is an extraction and the second because it is a list

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
10,The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
12,For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN

In [47]:
bond.iloc[4:8] # this gives you four up to 8.  It is not inclusive

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
5,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
6,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
7,Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8

In [48]:
bond.iloc[:6] #gives you the first six rows

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
5,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [49]:
bond.iloc[20:] # gives you row 20 until the end

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
21,Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
22,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
26,No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0

## Retrieve Rows by Index Label with loc Accessor
- The `loc` accessor retrieves one or more rows by index label.
- Provide a pair of square brackets after the accessor.

In [97]:
bond = pd.read_csv("jamesbond.csv", index_col="Film")
bond = bond.sort_index()
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [90]:
bond.loc["Dr. No"]

Year                          1962
Actor                 Sean Connery
Director             Terence Young
Box Office                   448.8
Budget                         7.0
Bond Actor Salary              0.6
Name: Dr. No, dtype: object

In [91]:
bond.loc["Casino Royale"]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [93]:
bond.loc[["Goldfinger", "Moonraker", "Casino Royale"]]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [98]:
bond.loc["Diamonds Are Forever":"Moonraker"]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN

In [101]:
bond.loc["GoldenEye":]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [102]:
bond.loc[:"Moonraker"]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN

In [105]:
bond.loc["Casino Royale":]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

## Second Arguments to loc and iloc Accessors
- The second value inside the square brackets targets the columns.
- The `iloc` requires numeric positions for rows and columns.
- The `loc` requires labels for rows and columns.

In [107]:
bond = pd.read_csv("jamesbond.csv", index_col="Film").sort_index()
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [112]:
bond.loc[["Diamonds Are Forever", "Thunderball"], ["Director", "Box Office"]]

                           Director  Box Office
Film
Diamonds Are Forever   Guy Hamilton       442.5
Thunderball           Terence Young       848.1

In [117]:
bond.info()

<class 'pandas.core.frame.DataFrame'>
Index: 27 entries, A View to a Kill to You Only Live Twice
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Year               27 non-null     int64
 1   Actor              27 non-null     object
 2   Director           27 non-null     object
 3   Box Office         27 non-null     float64
 4   Budget             27 non-null     float64
 5   Bond Actor Salary  20 non-null     float64
dtypes: float64(3), int64(1), object(2)
memory usage: 2.5+ KB

In [119]:
bond["Profit"] = bond["Box Office"] - bond["Budget"]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary,Profit
Film,,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1,220.7
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3,436.2
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN,230.0
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8,407.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9,311.2
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6,441.8
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN,389.2
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6,531.2
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1,441.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2,801.8
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9,194.2
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN,429.5
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN,443.5
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN,294.0
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0,473.2
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8,319.9
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6,254.2
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1,332.8
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5,773.3
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0,520.4
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2,244.7
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN,306.3
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN,487.9
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5,281.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7,806.2
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0,329.3
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4,454.3

In [121]:
bond.iloc[0, 2]

'John Glen'

In [122]:
bond.iloc[3, 5]

5.8

In [123]:
bond.iloc[[0, 2], 3]

Film
A View to a Kill    275.2
Casino Royale       315.0
Name: Box Office, dtype: float64

In [125]:
bond.iloc[[0, 2], [3, 5]]

                  Box Office  Bond Actor Salary
Film
A View to a Kill       275.2                9.1
Casino Royale          315.0                NaN

## Overwrite Value in a DataFrame
- Use the `iloc` or `loc` accessor on the **DataFrame** to target a value, then provide the equal sign and a new value.

In [132]:
bond = pd.read_csv("jamesbond.csv", index_col="Film").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [139]:
#bond["Actor"].loc["Diamonds Are Forever"] = "Sir Sean Connery" This code will lead to a warning because we are using a slice bond["Actor"] before the loc
bond.loc["Diamonds Are Forever", "Actor"] = "Sir Sean Connery" # this is the correct code.  Loc is at the top level or the parent object
bond.loc["Diamonds Are Forever", ["Actor"]]

Actor    Sir Sean Connery
Name: Diamonds Are Forever, dtype: object

In [140]:
bond.iloc[3,1]

'Sir Sean Connery'

##  Overwrite Multiple Values in a DataFrame
- The `replace` method replaces all occurrences of a **Series** value with another value (think of it like "Find and Replace").
- To overwrite multiple values in a **DataFrame**, remember to use an accessor on the **DataFrame** itself.
- Accessors like `loc` and `iloc` can accept Boolean Series. Use them to target the values to overwrite.

In [144]:
bond = pd.read_csv("jamesbond.csv", index_col="Film").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [146]:
bond["Actor"].replace("Sean Connery", "Sir Sean Connery") #this is a series or copy so it does not change the original dataset so it is temporary
# replace is like search and replace. The first argument is what youare looking for and the second is what you will replace it with

Film
A View to a Kill                        Roger Moore
Casino Royale                          Daniel Craig
Casino Royale                           David Niven
Diamonds Are Forever               Sir Sean Connery
Die Another Day                      Pierce Brosnan
Dr. No                             Sir Sean Connery
For Your Eyes Only                      Roger Moore
From Russia with Love              Sir Sean Connery
GoldenEye                            Pierce Brosnan
Goldfinger                         Sir Sean Connery
Licence to Kill                      Timothy Dalton
Live and Let Die                        Roger Moore
Moonraker                               Roger Moore
Never Say Never Again              Sir Sean Connery
No Time to Die                         Daniel Craig
Octopussy                               Roger Moore
On Her Majesty's Secret Service      George Lazenby
Quantum of Solace                      Daniel Craig
Skyfall                                Daniel Craig
Spectre                                Daniel Craig
The Living Daylights                 Timothy Dalton
The Man with the Golden Gun             Roger Moore
The Spy Who Loved Me                    Roger Moore
The World Is Not Enough              Pierce Brosnan
Thunderball                        Sir Sean Connery
Tomorrow Never Dies                  Pierce Brosnan
You Only Live Twice                Sir Sean Connery
Name: Actor, dtype: object

In [148]:
bond["Actor"] = bond["Actor"].replace("Sean Connery", "Sir Sean Connery") # this is permanent
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sir Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sir Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sir Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sir Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sir Sean Connery,Irvin Kershner,380.0,86.0,NaN
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sir Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sir Sean Connery,Lewis Gilbert,514.2,59.9,4.4

## Rename Index Labels or Columns in a DataFrame
- The `rename` method accepts a dictionary for either its `columns` or `index` parameters.
- The dictionary keys represent the existing names and the values represent the new names.
- We can replace all columns by overwriting the **DataFrame's** `columns` attribute.

In [166]:
bond = pd.read_csv("jamesbond.csv", index_col="Film").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [167]:
bond = bond.rename(columns={"Year":"Year Released", "Box Office": "Revenue", "Budget": "Cost"})
bond["Profit"] = bond["Revenue"] - bond["Cost"]
bond

,Year Released,Actor,Director,Revenue,Cost,Bond Actor Salary,Profit
Film,,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1,220.7
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3,436.2
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN,230.0
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8,407.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9,311.2
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6,441.8
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN,389.2
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6,531.2
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1,441.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2,801.8
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9,194.2
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN,429.5
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN,443.5
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN,294.0
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0,473.2
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8,319.9
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6,254.2
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1,332.8
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5,773.3
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0,520.4
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2,244.7
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN,306.3
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN,487.9
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5,281.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7,806.2
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0,329.3
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4,454.3

In [171]:
changes = {
    "Dr. No": "Dr No",
    "GoldenEye": "Golden Eye",
    "The World Is Not Enough": "Best Ever"
}

bond = bond.rename(index=changes)
bond.sort_index()

,Year Released,Actor,Director,Revenue,Cost,Bond Actor Salary,Profit
Film,,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1,220.7
Best Ever,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5,281.2
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3,436.2
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN,230.0
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8,407.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9,311.2
Dr No,1962,Sean Connery,Terence Young,448.8,7.0,0.6,441.8
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN,389.2
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6,531.2
Golden Eye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1,441.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2,801.8
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9,194.2
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN,429.5
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN,443.5
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN,294.0
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0,473.2
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8,319.9
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6,254.2
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1,332.8
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5,773.3
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0,520.4
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2,244.7
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN,306.3
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN,487.9
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7,806.2
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0,329.3
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4,454.3

In [175]:
bond = bond.columns = ["Year", "Bond Guy", "Boss", "Rev", "Cost", "Salary", "Profit"]

AttributeError: 'list' object has no attribute 'columns'

In [174]:
bond.columns

Index(['Year', 'Bond Guy', 'Boss', 'Rev', 'Cost', 'Salary', 'Profit'], dtype='object')

## Delete Rows or Columns from a DataFrame
- The `drop` method deletes one or more rows/columns from a **DataFrame**.
- Pass the `index` or `columns` parameters a list of the column names to remove.
- The `pop` method removes and returns a single **Series** (it mutates the **DataFrame** in the process).
- Python's `del` keyword also removes a single **Series**.

In [176]:
bond = pd.read_csv("jamesbond.csv", index_col="Film").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [178]:
bond.drop(columns=["Box Office", "Budget"]) # columns is used to remove columns

,Year,Actor,Director,Bond Actor Salary
Film,,,,
A View to a Kill,1985,Roger Moore,John Glen,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,3.3
Casino Royale,1967,David Niven,Ken Hughes,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,17.9
Dr. No,1962,Sean Connery,Terence Young,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,NaN
From Russia with Love,1963,Sean Connery,Terence Young,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,NaN
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,25.0
Octopussy,1983,Roger Moore,John Glen,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,14.5
Spectre,2015,Daniel Craig,Sam Mendes,30.0
The Living Daylights,1987,Timothy Dalton,John Glen,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,13.5
Thunderball,1965,Sean Connery,Terence Young,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,4.4

In [181]:
bond = bond.drop(index=["No Time to Die"]) # index is used to delete rows

In [183]:
bond.drop(index=["Casino Royale"], columns=["Box Office", "Budget"])

,Year,Actor,Director,Bond Actor Salary
Film,,,,
A View to a Kill,1985,Roger Moore,John Glen,9.1
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,17.9
Dr. No,1962,Sean Connery,Terence Young,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,NaN
From Russia with Love,1963,Sean Connery,Terence Young,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,NaN
Octopussy,1983,Roger Moore,John Glen,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,14.5
Spectre,2015,Daniel Craig,Sam Mendes,30.0
The Living Daylights,1987,Timothy Dalton,John Glen,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,13.5
Thunderball,1965,Sean Connery,Terence Young,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,4.4

In [184]:
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [185]:
bond.pop("Actor")

Film
A View to a Kill                      Roger Moore
Casino Royale                        Daniel Craig
Casino Royale                         David Niven
Diamonds Are Forever                 Sean Connery
Die Another Day                    Pierce Brosnan
Dr. No                               Sean Connery
For Your Eyes Only                    Roger Moore
From Russia with Love                Sean Connery
GoldenEye                          Pierce Brosnan
Goldfinger                           Sean Connery
Licence to Kill                    Timothy Dalton
Live and Let Die                      Roger Moore
Moonraker                             Roger Moore
Never Say Never Again                Sean Connery
Octopussy                             Roger Moore
On Her Majesty's Secret Service    George Lazenby
Quantum of Solace                    Daniel Craig
Skyfall                              Daniel Craig
Spectre                              Daniel Craig
The Living Daylights               Timothy Dalton
The Man with the Golden Gun           Roger Moore
The Spy Who Loved Me                  Roger Moore
The World Is Not Enough            Pierce Brosnan
Thunderball                          Sean Connery
Tomorrow Never Dies                Pierce Brosnan
You Only Live Twice                  Sean Connery
Name: Actor, dtype: object

In [186]:
bond

,Year,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,
A View to a Kill,1985,John Glen,275.2,54.5,9.1
Casino Royale,2006,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Sam Mendes,726.7,206.3,30.0
The Living Daylights,1987,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Lewis Gilbert,514.2,59.9,4.4

In [187]:
del bond["Year"]

In [188]:
bond.head()

                             Director  Box Office  Budget  Bond Actor Salary
Film
A View to a Kill            John Glen       275.2    54.5                9.1
Casino Royale         Martin Campbell       581.5   145.3                3.3
Casino Royale              Ken Hughes       315.0    85.0                NaN
Diamonds Are Forever     Guy Hamilton       442.5    34.7                5.8
Die Another Day          Lee Tamahori       465.4   154.2               17.9

## Create Random Sample with the sample Method
- The `sample` method returns a specified one or more random rows from the **DataFrame**.
- Customize the `axis` parameter to extract random columns.

In [ ]:
bond = pd.read_csv("jamesbond.csv", index_col="Film").sort_index()
bond.head()

In [193]:
bond.sample(n=5) # they are pulled not in order so they listed by when they were pulled

,Director,Box Office,Budget,Bond Actor Salary
Film,,,,
Moonraker,Lewis Gilbert,535.0,91.5,NaN
GoldenEye,Martin Campbell,518.5,76.9,5.1
Spectre,Sam Mendes,726.7,206.3,30.0
Thunderball,Terence Young,848.1,41.9,4.7
The World Is Not Enough,Michael Apted,439.5,158.3,13.5

In [194]:
bond.sample(n=2, axis="columns") # you can also randomly select columns.

                                           Director  Box Office
Film
A View to a Kill                          John Glen       275.2
Casino Royale                       Martin Campbell       581.5
Casino Royale                            Ken Hughes       315.0
Diamonds Are Forever                   Guy Hamilton       442.5
Die Another Day                        Lee Tamahori       465.4
Dr. No                                Terence Young       448.8
For Your Eyes Only                        John Glen       449.4
From Russia with Love                 Terence Young       543.8
GoldenEye                           Martin Campbell       518.5
Goldfinger                             Guy Hamilton       820.4
Licence to Kill                           John Glen       250.9
Live and Let Die                       Guy Hamilton       460.3
Moonraker                             Lewis Gilbert       535.0
Never Say Never Again                Irvin Kershner       380.0
Octopussy                                 John Glen       373.8
On Her Majesty's Secret Service       Peter R. Hunt       291.5
Quantum of Solace                      Marc Forster       514.2
Skyfall                                  Sam Mendes       943.5
Spectre                                  Sam Mendes       726.7
The Living Daylights                      John Glen       313.5
The Man with the Golden Gun            Guy Hamilton       334.0
The Spy Who Loved Me                  Lewis Gilbert       533.0
The World Is Not Enough               Michael Apted       439.5
Thunderball                           Terence Young       848.1
Tomorrow Never Dies              Roger Spottiswoode       463.2
You Only Live Twice                   Lewis Gilbert       514.2

## The nsmallest and nlargest Methods
- The `nlargest` method returns a specified number of rows with the largest values from a given column.
- The `nsmallest` method returns rows with the smallest values from a given column.
- The `nlargest` and `nsmallest` methods are more efficient than sorting the entire **DataFrame**.

In [195]:
bond = pd.read_csv("jamesbond.csv", index_col="Film").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [198]:
# retrieve top 4 box office values
bond.sort_values("Box Office", ascending=False).head(4)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0

In [203]:
# more efficient method, but only works on numeric data.  Get an error with text. Need to use sort_values with text
bond.nlargest(n=4, columns="Box Office") # this method provides the four largest Box Office values for the dataframe
bond["Box Office"].nlargest(4) # this is a series and gives the top four but just the series or column and not the entire df

Film
Skyfall           943.5
Thunderball       848.1
Goldfinger        820.4
No Time to Die    774.2
Name: Box Office, dtype: float64

## Filtering with the where Method
- Similar to square brackets or `loc`, the `where` method filters the original `DataFrame` with a Boolean Series.
- Pandas will populate rows that do **not** match the criteria with `NaN` values.
- Leaving in the `NaN` values can be advantageous for certain merge and visualization operations.

In [204]:
bond = pd.read_csv("jamesbond.csv", index_col="Film").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [ ]:
# rows that have a false in the boolean series but will populated with a NaN value. All rows are retrieved

In [211]:
sean_connery = bond["Actor"] == "Sean Connery"
bond[sean_connery] # 1 way to filter on sean
bond.loc[sean_connery] # 2 way to filter
bond.where(sean_connery)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,NaN,NaN,NaN,NaN,NaN,NaN
Casino Royale,NaN,NaN,NaN,NaN,NaN,NaN
Casino Royale,NaN,NaN,NaN,NaN,NaN,NaN
Diamonds Are Forever,1971.0,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,NaN,NaN,NaN,NaN,NaN,NaN
Dr. No,1962.0,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,NaN,NaN,NaN,NaN,NaN,NaN
From Russia with Love,1963.0,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,NaN,NaN,NaN,NaN,NaN,NaN
Goldfinger,1964.0,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,NaN,NaN,NaN,NaN,NaN,NaN
Live and Let Die,NaN,NaN,NaN,NaN,NaN,NaN
Moonraker,NaN,NaN,NaN,NaN,NaN,NaN
Never Say Never Again,1983.0,Sean Connery,Irvin Kershner,380.0,86.0,NaN
No Time to Die,NaN,NaN,NaN,NaN,NaN,NaN
Octopussy,NaN,NaN,NaN,NaN,NaN,NaN
On Her Majesty's Secret Service,NaN,NaN,NaN,NaN,NaN,NaN
Quantum of Solace,NaN,NaN,NaN,NaN,NaN,NaN
Skyfall,NaN,NaN,NaN,NaN,NaN,NaN
Spectre,NaN,NaN,NaN,NaN,NaN,NaN
The Living Daylights,NaN,NaN,NaN,NaN,NaN,NaN
The Man with the Golden Gun,NaN,NaN,NaN,NaN,NaN,NaN
The Spy Who Loved Me,NaN,NaN,NaN,NaN,NaN,NaN
The World Is Not Enough,NaN,NaN,NaN,NaN,NaN,NaN
Thunderball,1965.0,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,NaN,NaN,NaN,NaN,NaN,NaN
You Only Live Twice,1967.0,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

## The apply Method with DataFrames
- The `apply` method invokes a function on every column or every row in the **DataFrame**.
- Pass the uninvoked function as the first argument to the `apply` method.
- Pass the `axis` parameter an argument of `"columns"` to invoke the function on every row.
- Pandas will pass in the row's values as a **Series** object. We can use accessors like `loc` and `iloc` to extract the column's values for that row.

In [212]:
bond = pd.read_csv("jamesbond.csv", index_col="Film").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [229]:
def rank_movie(row):
    year = row.loc["Year"]
    actor = row.loc["Actor"]
    budget = row.loc["Budget"]

    if year >= 1980 and year < 1990:
        return "Great 80's Flick!"

    if actor == "Pierce Brosnan":
        return "Best Bond!"

    if budget > 100:
        return "Cha Ching!"

    return "Boring"

bond.apply(rank_movie, axis="columns")

Film
A View to a Kill                   Great 80's Flick!
Casino Royale                             Cha Ching!
Casino Royale                                 Boring
Diamonds Are Forever                          Boring
Die Another Day                           Best Bond!
Dr. No                                        Boring
For Your Eyes Only                 Great 80's Flick!
From Russia with Love                         Boring
GoldenEye                                 Best Bond!
Goldfinger                                    Boring
Licence to Kill                    Great 80's Flick!
Live and Let Die                              Boring
Moonraker                                     Boring
Never Say Never Again              Great 80's Flick!
No Time to Die                            Cha Ching!
Octopussy                          Great 80's Flick!
On Her Majesty's Secret Service               Boring
Quantum of Solace                         Cha Ching!
Skyfall                                   Cha Ching!
Spectre                                   Cha Ching!
The Living Daylights               Great 80's Flick!
The Man with the Golden Gun                   Boring
The Spy Who Loved Me                          Boring
The World Is Not Enough                   Best Bond!
Thunderball                                   Boring
Tomorrow Never Dies                       Best Bond!
You Only Live Twice                           Boring
dtype: object